/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Templates;
import Model.ProductosProveedor;
import Controller.ProveedorDAO;
import java.util.ArrayList;


import javax.swing.table.DefaultTableModel;
import Model.Producto;
import Model.ProductosProveedor;
import java.awt.event.ItemEvent;
/**
 *
 * @author Bastian
 */
public class GestionProductosAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Catalogo
     */
    public String Proveedor;
    public String rut;
    public GestionProductosAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
        LlenarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableLista = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JLabel();
        CbxProveedores = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Precio", "Marca", "Stock"
            }
        ));
        tableLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableListaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableLista);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 710, 280));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(java.awt.SystemColor.control);
        jLabel7.setText("Gestión de productos");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volver.png"))); // NOI18N
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, -1, -1));

        CbxProveedores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CbxProveedoresItemStateChanged(evt);
            }
        });
        CbxProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxProveedoresActionPerformed(evt);
            }
        });
        getContentPane().add(CbxProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 160, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Proveedor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 20));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/abstract-red-gradient-background-red-orange-curve-wallpaper-free-vector.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        this.setVisible(false);
        Main ma =new Main();
        ma.rut = this.rut;
        ma.setVisible(true);
    }//GEN-LAST:event_btnVolverMouseClicked

    private void CbxProveedoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CbxProveedoresItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
          String item = (String)evt.getItem();
          this.Proveedor = item;
          LlenarTodo(this.Proveedor);
        }
    }//GEN-LAST:event_CbxProveedoresItemStateChanged

    private void CbxProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxProveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxProveedoresActionPerformed

    private void tableListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListaMouseClicked
        int seleccionar = tableLista.rowAtPoint(evt.getPoint());
        String Id = String.valueOf(tableLista.getValueAt(seleccionar, 0));
        String Nombre = String.valueOf(tableLista.getValueAt(seleccionar, 1));
        String Descripcion = String.valueOf(tableLista.getValueAt(seleccionar, 2));
        String Familia = String.valueOf(tableLista.getValueAt(seleccionar, 3));
        String Fecha = String.valueOf(tableLista.getValueAt(seleccionar, 4));
        String precio = String.valueOf(tableLista.getValueAt(seleccionar, 5));
        Orden or = new Orden();
        or.txtProducto.setText(Id);
        or.TxtNombre.setText(Nombre);
        or.TxtDetalle.setText(Descripcion);
        or.TxtFamilia.setText(Familia);
        or.TxtFecha.setText(Fecha);
        or.precio = Integer.valueOf(precio);
        or.Txtprecio.setText(precio);
        or.rut = this.rut;
        or.proveedor = this.Proveedor;
        or.setVisible(true);
    }//GEN-LAST:event_tableListaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionProductosAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionProductosAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionProductosAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionProductosAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionProductosAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> CbxProveedores;
    private javax.swing.JLabel btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tableLista;
    // End of variables declaration//GEN-END:variables

    private void LlenarTodo(String nombre) {
         try {
            ArrayList<Model.ProductosProveedor> listado= new ProveedorDAO().GetProductosProveedor(nombre);
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Id");
            modelo.addColumn("Nombre");
            modelo.addColumn("Descripcion");
            modelo.addColumn("Familia");
            modelo.addColumn("Fecha");
            modelo.addColumn("Precio");
            modelo.addColumn("Stock");
            String[] fila = new String[7];
            tableLista.setModel(modelo);
            for(Model.ProductosProveedor item:listado){
                fila[0]=String.valueOf(item.getID());
                fila[1]=item.getNombre();
                fila[2]=item.getDescripcion();
                fila[3]=item.getFamilia();
                fila[4]=item.getFecha_Ve().substring(0, 10);
                fila[5]=String.valueOf(item.getPrecio());
                fila[6]=String.valueOf(item.getStock());
                modelo.addRow(fila);
            }
            tableLista.setModel(modelo);
        } catch (Exception e) {
        }
    }
    private void LlenarCombo(){
       ArrayList<Model.Proveedor> listado = new ProveedorDAO().Listado();
       for(Model.Proveedor item:listado){
           CbxProveedores.addItem(item.getNombre());
       }
    }
}
