/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Templates;

/**
 *
 * @author Bastian
 */
public class ModificarProducto extends javax.swing.JFrame {

    /**
     * Creates new form ConfirmacionOrden
     */
    public ModificarProducto() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtProductoNuevo = new javax.swing.JTextField();
        txtProveedorNuevo = new javax.swing.JTextField();
        txtMarcaNueva = new javax.swing.JTextField();
        txtPrecioNuevo = new javax.swing.JTextField();
        cmbProducto = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtCantidadNueva = new javax.swing.JTextField();
        cmbProveedor = new javax.swing.JComboBox<>();
        btnVolver = new javax.swing.JLabel();
        btnCarrito = new javax.swing.JLabel();
        txtCantidadActual = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtPrecioActual = new javax.swing.JTextField();
        txtMarcaActual = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtProductoActual = new javax.swing.JTextField();
        txtProveedorActual = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setForeground(java.awt.SystemColor.control);
        jLabel23.setText("Producto nuevo: ");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel25.setForeground(java.awt.SystemColor.control);
        jLabel25.setText("Precio nuevo:");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel26.setForeground(java.awt.SystemColor.control);
        jLabel26.setText("Cantidad nueva:");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel24.setForeground(java.awt.SystemColor.control);
        jLabel24.setText("Marca nueva:");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        txtProductoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductoNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(txtProductoNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 140, -1));
        getContentPane().add(txtProveedorNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 140, -1));
        getContentPane().add(txtMarcaNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 140, -1));
        getContentPane().add(txtPrecioNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 140, -1));

        cmbProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        getContentPane().add(cmbProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 100, -1));

        jLabel2.setForeground(java.awt.SystemColor.control);
        jLabel2.setText("Proveedor nuevo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));
        getContentPane().add(txtCantidadNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 140, -1));

        cmbProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        getContentPane().add(cmbProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 100, -1));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volver.png"))); // NOI18N
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, -1, -1));

        btnCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modificar.png"))); // NOI18N
        btnCarrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));
        getContentPane().add(txtCantidadActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 140, -1));

        jLabel27.setForeground(java.awt.SystemColor.control);
        jLabel27.setText("Cantidad actual:");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, -1));

        jLabel28.setForeground(java.awt.SystemColor.control);
        jLabel28.setText("Precio actual:");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, -1));
        getContentPane().add(txtPrecioActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 140, -1));
        getContentPane().add(txtMarcaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 140, -1));

        jLabel29.setForeground(java.awt.SystemColor.control);
        jLabel29.setText("Marca actual:");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        jLabel3.setForeground(java.awt.SystemColor.control);
        jLabel3.setText("Proveedor actual:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));

        txtProductoActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductoActualActionPerformed(evt);
            }
        });
        getContentPane().add(txtProductoActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 140, -1));
        getContentPane().add(txtProveedorActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 140, -1));

        jLabel30.setForeground(java.awt.SystemColor.control);
        jLabel30.setText("Producto actual: ");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/abstract-red-gradient-background-red-orange-curve-wallpaper-free-vector.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProductoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductoNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductoNuevoActionPerformed

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
    this.setVisible(false);
    new GestionProductosAdmin().setVisible(true);
    }//GEN-LAST:event_btnVolverMouseClicked

    private void txtProductoActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductoActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductoActualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCarrito;
    private javax.swing.JLabel btnVolver;
    private javax.swing.JComboBox<String> cmbProducto;
    private javax.swing.JComboBox<String> cmbProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JTextField txtCantidadActual;
    private javax.swing.JTextField txtCantidadNueva;
    private javax.swing.JTextField txtMarcaActual;
    private javax.swing.JTextField txtMarcaNueva;
    private javax.swing.JTextField txtPrecioActual;
    private javax.swing.JTextField txtPrecioNuevo;
    private javax.swing.JTextField txtProductoActual;
    private javax.swing.JTextField txtProductoNuevo;
    private javax.swing.JTextField txtProveedorActual;
    private javax.swing.JTextField txtProveedorNuevo;
    // End of variables declaration//GEN-END:variables
}
