/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Templates;

import Controller.EmpleadoDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Bastian
 */
public class Orden extends javax.swing.JFrame {

    /**
     * Creates new form ConfirmacionOrden
     */
    public String proveedor;
    public int contador;
    public int precio;
    public int precioTotal;
    public String rut;
    public Orden() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        TxtNombre = new javax.swing.JTextField();
        TxtDetalle = new javax.swing.JTextField();
        TxtCantidad = new javax.swing.JTextField();
        btnVolver = new javax.swing.JLabel();
        btnCarrito = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        TxtFecha = new javax.swing.JTextField();
        TxtFamilia = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        Txtprecio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setForeground(java.awt.SystemColor.control);
        jLabel23.setText("ID Producto");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel25.setForeground(java.awt.SystemColor.control);
        jLabel25.setText("Detalle");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel26.setForeground(java.awt.SystemColor.control);
        jLabel26.setText("Cantidad:");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel24.setForeground(java.awt.SystemColor.control);
        jLabel24.setText("Nombre");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        txtProducto.setEditable(false);
        txtProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductoActionPerformed(evt);
            }
        });
        getContentPane().add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 250, -1));

        TxtNombre.setEditable(false);
        getContentPane().add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 250, -1));

        TxtDetalle.setEditable(false);
        getContentPane().add(TxtDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 250, -1));

        TxtCantidad.setEditable(false);
        TxtCantidad.setText("1");
        TxtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCantidadActionPerformed(evt);
            }
        });
        getContentPane().add(TxtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 250, -1));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volver.png"))); // NOI18N
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, -1, -1));

        btnCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrito_1.png"))); // NOI18N
        btnCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarritoMouseClicked(evt);
            }
        });
        getContentPane().add(btnCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel27.setForeground(java.awt.SystemColor.control);
        jLabel27.setText("Fecha Vencimiento");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        TxtFecha.setEditable(false);
        getContentPane().add(TxtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 250, -1));

        TxtFamilia.setEditable(false);
        getContentPane().add(TxtFamilia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 250, -1));

        jLabel28.setForeground(java.awt.SystemColor.control);
        jLabel28.setText("Familia");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jButton1.setText("-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, -1));

        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, -1, -1));

        jLabel29.setForeground(java.awt.SystemColor.control);
        jLabel29.setText("Precio");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        Txtprecio.setEditable(false);
        getContentPane().add(Txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 250, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/abstract-red-gradient-background-red-orange-curve-wallpaper-free-vector.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductoActionPerformed

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
    this.setVisible(false);
    }//GEN-LAST:event_btnVolverMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.contador = this.contador+1;
        this.precioTotal = this.precio*this.contador;
        Txtprecio.setText(String.valueOf(this.precioTotal));
        TxtCantidad.setText(String.valueOf(this.contador));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if (this.contador > 1) {
            this.contador = this.contador-1;
            this.precioTotal = this.precio*this.contador;
            Txtprecio.setText(String.valueOf(this.precioTotal));
            TxtCantidad.setText(String.valueOf(this.contador));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TxtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCantidadActionPerformed

    private void btnCarritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarritoMouseClicked
       EmpleadoDAO emp =new EmpleadoDAO();
       int idProducto = Integer.valueOf(txtProducto.getText());
       String nombre = TxtNombre.getText();
       String descripcion = TxtDetalle.getText();
       int idEmpleado = Integer.valueOf(this.rut);
       String idproveedor = this.proveedor;
       int cantidad = Integer.valueOf(TxtCantidad.getText());
       int precio = Integer.valueOf(Txtprecio.getText());
        System.out.println(idProducto);
        System.out.println(nombre);
        System.out.println(descripcion);
        System.out.println(idEmpleado);
        System.out.println(precio);
        System.out.println(cantidad);
       int respu = emp.RealizarPedido(idProducto,nombre,descripcion,idEmpleado,idproveedor,precio,cantidad);
        if (respu == 1) {
            JOptionPane.showMessageDialog( null,"Pedido Realizado");
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnCarritoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Orden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Orden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Orden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Orden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Orden().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField TxtCantidad;
    public javax.swing.JTextField TxtDetalle;
    public javax.swing.JTextField TxtFamilia;
    public javax.swing.JTextField TxtFecha;
    public javax.swing.JTextField TxtNombre;
    public javax.swing.JTextField Txtprecio;
    private javax.swing.JLabel btnCarrito;
    private javax.swing.JLabel btnVolver;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    public javax.swing.JTextField txtProducto;
    // End of variables declaration//GEN-END:variables
}
